### ISSUE TITLE
Add .gitignore 

### ISSUE THREAD

**Issue by mattlisiv** [daniellesuper/elevationsoftware#6]
- Create .gitignore and remove all included files from repository including `node_modules`
https://www.chaseadams.io/posts/my-gitignore-conventions/
- Verify you can still run `npm` commands without issue when cloning into a new folder. This means all your packages are correctly in the package.json

**Comment by daniellesuper** [comment]
Ignored all logs, ds_store and node-modules. Cloned it in a new folder ran npm install, npm start and all is functioning. Are there any other files/directories I should be excluding ?

**Comment by mattlisiv** [comment]
Cool, all good for now. If more files arise that need to be ignored, just add to gitignore before commit.
