### ISSUE TITLE
Side Navigation Not Working

### ISSUE THREAD

**Issue by mattlisiv** [daniellesuper/elevationsoftware#7]
With the most recent navigation changes, I believe the side hamburger menu no longer functions. Also, I think it make sense move it to the right, so the logo stays in a consistent place.

**Comment by daniellesuper** [comment]
Should I use a useState hook and handle all of the click events for the hamburger icon and sidedrawer in the DefaultLayout function in _layout/index.js or should those events be defined elsewhere and passed to the function?

**Comment by mattlisiv** [comment]
If you can utilize the `useState`hook to handle all events that would be the cleanest and simplest way IMO
